# -*- coding: utf-8 -*-
"""OCR_MAX_MIN.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1mdKWC07EoPmVbnZ2U_94xDi5dQQBPf7V
"""

#!sudo apt install tesseract-ocr
#!pip install pytesseract

import pytesseract
import shutil
import os
import random
try:
    from PIL import Image
except ImportError:
    import Image
from google.colab import files

#uploaded = files.upload()
image_path_in_colab = 'test7.jpg'
extractedInformation = pytesseract.image_to_string(Image.open(image_path_in_colab))
print(extractedInformation)
print(pytesseract.image_to_boxes(Image.open(image_path_in_colab)))

